baseURL = 'https://hugo-overflow-identity.pages.dev/'
languageCode = 'en-us'
title = "Yosemite National Park"
themesDir = "../.."
theme = "hugo-overflow-identity"

[params]
authorName = 'Setu Shah'
description = "A demo page for the Hugo Overflow Identity theme."

[params.footer]
copyrightOwner = "Setu Shah"
copyrightStartYear = "2020"

[[params.footer.social]]
link = "mailto:email@domain.com"
icon = "far fa-envelope"
name = "Email"

[[params.footer.social]]
link = "https://www.github.com/"
icon = "fab fa-github"
name = "GitHub"

[[params.footer.social]]
link = "https://twitter.com/"
icon = "fab fa-twitter"
name = "Twitter"

[[params.footer.social]]
link = "https://www.linkedin.com/"
icon = "fab fa-linkedin"
name = "LinkedIn"

[[params.footer.social]]
link = "https://facebook.com/"
icon = "fab fa-facebook"
name = "Facebook"

[[params.footer.social]]
link = "https://instagram.com/"
icon = "fab fa-instagram"
name = "Instagram"
